### ISSUE TITLE
Error related to lsp configs

### ISSUE THREAD

**Issue by MikaelElkiaer** [milkias17/reloader.nvim#3]
Hi, great work so far!

I am seeing the error below on `:Reload`.
I have not looked into the details yet, but it seems there might be some lsp config that does not look as expected.
My config can be seen here: https://github.com/mikaelelkiaer/nvim-config

```
Error executing vim.schedule lua callback: .../pack/packer/opt/reloader.nvim/lua/reload-nvim/utils.lua:78: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
        [C]: in function 'ipairs'
        .../pack/packer/opt/reloader.nvim/lua/reload-nvim/utils.lua:78: in function 'table_contains'
        .../pack/packer/opt/reloader.nvim/lua/reload-nvim/utils.lua:154: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by milkias17** [comment]
Thanks. And about the error I believe this error happens when a client for some reason doesn't have a filetypes in its config, in any case I have pushed a change which should take care of this issue.

**Comment by MikaelElkiaer** [comment]
@milkias17 Thanks! Works like a charm.
